### PR TITLE
docs: add readme

### PR DESCRIPTION
**Pull request by cdrage**
docs: add readme

Adds the initial readme

Closes https://github.com/containers/podman-desktop/issues/7634

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
@deboer-tim @benoitf

**Comment by benoitf** [comment]
I may have missed the PR with the code but IMHO there should be no RPC class

just use the basic postMessage stuff

**Comment by cdrage** [comment]
> I may have missed the PR with the code but IMHO there should be no RPC class
> 
> just use the basic postMessage stuff

Apologizes, I put it in the initial commit since it was (mostly) based on https://github.com/containers/podman-desktop-extension-template-webview

Are we sure we do not want to use our MessageProxy code? We do use postMessage in the RPC / our shared code: https://github.com/containers/podman-desktop-extension-template-webview/blob/main/packages/shared/src/messages/MessageProxy.ts#L83

This provides much easier / method-based / straight forward implementation. 

Using the basic postMessage I feel would be limiting.

Just wanted to double check as this is different than what @feloy proposed in his repo: https://github.com/containers/podman-desktop-extension-template-webview

**Comment by benoitf** [comment]
like also do we need Svelte in the frontend or just an hello world html saying 'Hello'

what's the rationale ?
Highlighting the API using a minimal example or trying to add a full blown with tons of code sample ?

**Comment by benoitf** [comment]
I would tend to disagree and have a very minimal sample, letting people choose on how they want to define or use inside their application

then there could be a more advanced example but here it's very hard to know what is really the 'example' and the minimal requirement

**Comment by feloy** [comment]
> I would tend to disagree and have a very minimal sample, letting people choose on how they want to define or use inside their application
> 
> then there could be a more advanced example but here it's very hard to know what is really the 'example' and the minimal requirement

The problem I can see with a very minimal frontend (with a simple static HTML page) is that it is not a real-world example. I tend to think that people who will write extensions won't be frontend experts, and may have troubles to build the frontend distribution artifacts without any example. With the provided vite configuration and build commands, they can see what is the expected result, and it would be easier to adapt the config/build for another toolkit/build system/etc.

**Comment by benoitf** [comment]
I would expect two kind of templates:
- the 'hello world' style
- the advanced one

**Comment by cdrage** [comment]
> > I would tend to disagree and have a very minimal sample, letting people choose on how they want to define or use inside their application
> > then there could be a more advanced example but here it's very hard to know what is really the 'example' and the minimal requirement
> 
> The problem I can see with a very minimal frontend (with a simple static HTML page) is that it is not a real-world example. I tend to think that people who will write extensions won't be frontend experts, and may have troubles to build the frontend distribution artifacts without any example. With the provided vite configuration and build commands, they can see what is the expected result, and it would be easier to adapt the config/build for another toolkit/build system/etc.

@benoitf @feloy 

I had a brief discussion with @benoitf and we are going to change this github repo so that it's a "full-template" that uses svelte, shared folder, etc to showcase storybook / how we do it with ai lab and bootc.

we'll have three repos:

podman-desktop-extension-minimal-template = VERY basic / non-production
podman-desktop-extension-webview-template = is minimal + webview index.html VERY BASIC / non-production
podman-desktop-extension-full-template = has svelte UI / this repo

**Comment by cdrage** [comment]
@benoitf ready for review, have changed naming in the readme to reflect that this is the "full" example.

**Review by benoitf — APPROVED** [review]
LGTM for the 1st iteration

maybe we should have direct links to the storybook page where it explains the different UI components, direct link to the .d.ts documentation and the github source

there is only one link to the documentation but it's for the publishing part

**Comment by cdrage** [comment]
> LGTM for the 1st iteration
> 
> maybe we should have direct links to the storybook page where it explains the different UI components, direct link to the .d.ts documentation and the github source
> 
> there is only one link to the documentation but it's for the publishing part

I agree, I will merge this as a starting point as we work on integrating storybook more (more information needs to go there too).

Will discuss more this week.

**Pull request merged**
